FROM node:22.21.0

# Setting working directory. All the path will be relative to WORKDIR
WORKDIR /usr/src/app

# Installing dependencies
COPY package*.json ./
RUN npm install

# Copying source files
COPY . .

# Declaring all arg to use for env in build time
ARG DATABASE_URL
ARG DB_HOST
ARG DB_PORT
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_DATABASE_NAME
ARG DB_SOCKET_PATH
ARG DB_CONNECTION_LIMIT
ARG DB_ACQUIRE_TIMEOUT_MS
ARG DB_CONNECT_TIMEOUT_MS
ARG SIGNING_SECRET
ARG JWT_SECRET
ARG AUDIENCE_JWT_SECRET
ARG SECRET_ENCRYPTION_KEY
ARG STORAGE_ROOT
ARG STORAGE_PUBLIC_BASE_URL
ARG MAX_UPLOAD_BYTES
ARG MAX_SIGNED_URL_TTL_SECONDS
ARG API_KEY_TIMESTAMP_DRIFT_MS
ARG VIRUSTOTAL_API_KEY
ARG VIRUSTOTAL_REQUIRED
ARG VIRUSTOTAL_TIMEOUT_MS
ARG VIRUSTOTAL_POLL_MS
ARG VIRUSTOTAL_MAX_POLLS
ARG VIRUSTOTAL_JOB_LOCK_TIMEOUT_MS
ARG VIRUSTOTAL_JOB_RETRY_DELAY_MS
ARG VIRUSTOTAL_MAX_JOB_ATTEMPTS
ARG VIRUSTOTAL_WORKER_POLL_MS
ARG NODE_ENV=production
# Declaring env from the arg value
ENV DATABASE_URL=${DATABASE_URL}
ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_DATABASE_NAME=${DB_DATABASE_NAME}
ENV DB_SOCKET_PATH=${DB_SOCKET_PATH}
ENV DB_CONNECTION_LIMIT=${DB_CONNECTION_LIMIT}
ENV DB_ACQUIRE_TIMEOUT_MS=${DB_ACQUIRE_TIMEOUT_MS}
ENV DB_CONNECT_TIMEOUT_MS=${DB_CONNECT_TIMEOUT_MS}
ENV SIGNING_SECRET=${SIGNING_SECRET}
ENV JWT_SECRET=${JWT_SECRET}
ENV AUDIENCE_JWT_SECRET=${AUDIENCE_JWT_SECRET}
ENV SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
ENV STORAGE_ROOT=${STORAGE_ROOT}
ENV STORAGE_PUBLIC_BASE_URL=${STORAGE_PUBLIC_BASE_URL}
ENV MAX_UPLOAD_BYTES=${MAX_UPLOAD_BYTES}
ENV MAX_SIGNED_URL_TTL_SECONDS=${MAX_SIGNED_URL_TTL_SECONDS}
ENV API_KEY_TIMESTAMP_DRIFT_MS=${API_KEY_TIMESTAMP_DRIFT_MS}
ENV VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY}
ENV VIRUSTOTAL_REQUIRED=${VIRUSTOTAL_REQUIRED}
ENV VIRUSTOTAL_TIMEOUT_MS=${VIRUSTOTAL_TIMEOUT_MS}
ENV VIRUSTOTAL_POLL_MS=${VIRUSTOTAL_POLL_MS}
ENV VIRUSTOTAL_MAX_POLLS=${VIRUSTOTAL_MAX_POLLS}
ENV VIRUSTOTAL_JOB_LOCK_TIMEOUT_MS=${VIRUSTOTAL_JOB_LOCK_TIMEOUT_MS}
ENV VIRUSTOTAL_JOB_RETRY_DELAY_MS=${VIRUSTOTAL_JOB_RETRY_DELAY_MS}
ENV VIRUSTOTAL_MAX_JOB_ATTEMPTS=${VIRUSTOTAL_MAX_JOB_ATTEMPTS}
ENV VIRUSTOTAL_WORKER_POLL_MS=${VIRUSTOTAL_WORKER_POLL_MS}
ENV NODE_ENV=${NODE_ENV}

# Generate Prisma client after source is available
RUN npx prisma generate

# Building app
RUN npm run build

# Running the app
CMD ["npm", "run", "start"]
