-- AlterTable
ALTER TABLE `medias`
  ADD COLUMN `scanStatus` ENUM('PENDING', 'CLEAN', 'MALICIOUS', 'FAILED') NOT NULL DEFAULT 'PENDING',
  ADD COLUMN `scanMessage` VARCHAR(191) NULL,
  ADD COLUMN `scanHash` VARCHAR(191) NULL,
  ADD COLUMN `scannedAt` DATETIME(3) NULL;
