-- AlterTable
ALTER TABLE `books` MODIFY `isAvailable` ENUM('AVAILABLE', 'PUBLIC', 'PRIVATE', 'RESTRICTED', 'REMOVE', 'RECOVERY', 'DRAFTED', 'PUBPLISHED') NOT NULL DEFAULT 'DRAFTED';

-- AlterTable
ALTER TABLE `medias` MODIFY `visibility` ENUM('AVAILABLE', 'PUBLIC', 'PRIVATE', 'RESTRICTED', 'REMOVE', 'RECOVERY', 'DRAFTED', 'PUBPLISHED') NOT NULL DEFAULT 'PUBLIC';

-- AlterTable
ALTER TABLE `spaces` MODIFY `status` ENUM('AVAILABLE', 'PUBLIC', 'PRIVATE', 'RESTRICTED', 'REMOVE', 'RECOVERY', 'DRAFTED', 'PUBPLISHED') NOT NULL DEFAULT 'AVAILABLE';
