-- AlterTable
ALTER TABLE `books` MODIFY `year` VARCHAR(191) NULL,
    MODIFY `isAvailable` ENUM('AVAILABLE', 'PUBLIC', 'PRIVATE', 'RESTRICTED', 'REMOVE', 'RECOVERY', 'DRAFTED') NOT NULL DEFAULT 'PUBLIC';

-- AlterTable
ALTER TABLE `medias` MODIFY `visibility` ENUM('AVAILABLE', 'PUBLIC', 'PRIVATE', 'RESTRICTED', 'REMOVE', 'RECOVERY', 'DRAFTED') NOT NULL DEFAULT 'PUBLIC';

-- AlterTable
ALTER TABLE `spaces` MODIFY `status` ENUM('AVAILABLE', 'PUBLIC', 'PRIVATE', 'RESTRICTED', 'REMOVE', 'RECOVERY', 'DRAFTED') NOT NULL DEFAULT 'AVAILABLE';
